# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 645b89a0075d6b2fc01a33aa9045957e6d1daae9968c2747aba577c0652fc8d950a844a64cd4bb278c5d34899448552f3b8ad739c7e89034e73ff6593f6c5a26

test:
  secret_key_base: e34652e9a0615ef3503364377ba51acf46688c9ad386ec6502838eafb65e57e862a73951fdfab96d7a2a39e515136e7757d5d6e5011bb15ce283d87122105395

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
